// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2ADsBKqwzJLTTljio6ktzh0B45MAQUCo',
    appId: '1:199339725352:web:48390f15816997cb179b1d',
    messagingSenderId: '199339725352',
    projectId: 'aravind-resume-29',
    authDomain: 'aravind-resume-29.firebaseapp.com',
    storageBucket: 'aravind-resume-29.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJmbtKnj7ptVkK4d31julJ18jwCQzwBzY',
    appId: '1:199339725352:android:b643a6dbe67324c6179b1d',
    messagingSenderId: '199339725352',
    projectId: 'aravind-resume-29',
    storageBucket: 'aravind-resume-29.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBx7P9rVkYvD1TZbTLUfHWnWSbtXqcshRI',
    appId: '1:199339725352:ios:3da6081cbc781da3179b1d',
    messagingSenderId: '199339725352',
    projectId: 'aravind-resume-29',
    storageBucket: 'aravind-resume-29.firebasestorage.app',
    iosBundleId: 'com.example.myResume',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBx7P9rVkYvD1TZbTLUfHWnWSbtXqcshRI',
    appId: '1:199339725352:ios:3da6081cbc781da3179b1d',
    messagingSenderId: '199339725352',
    projectId: 'aravind-resume-29',
    storageBucket: 'aravind-resume-29.firebasestorage.app',
    iosBundleId: 'com.example.myResume',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2ADsBKqwzJLTTljio6ktzh0B45MAQUCo',
    appId: '1:199339725352:web:eedf39d74f7af7a0179b1d',
    messagingSenderId: '199339725352',
    projectId: 'aravind-resume-29',
    authDomain: 'aravind-resume-29.firebaseapp.com',
    storageBucket: 'aravind-resume-29.firebasestorage.app',
  );
}
